### ISSUE TITLE
Collection tab bugs out

### ISSUE THREAD

**Issue by RadsWa** [Kiatra/BlizzMove#80] opened 2021-11-08 10:10 UTC
Hi, every addon except this one off, collection panel bugs out if you try and move it, become unresponsive and greys out buttons, you have to re-open it again and don't mis-click anything to use the panels, noticed it around 2 days ago so the 5th in the US

**Comment by Numynum** [comment] 2021-11-08 14:40
duplicate of #79

**Closed by Numynum** 2021-11-08 14:40 UTC
