### ISSUE TITLE
Can't move Transmogrify, Mounts/Pet Journal/Toy Box/Heirlooms/Appearances frames

### ISSUE THREAD

**Issue by speedwaystar** [Kiatra/BlizzMove#47] opened 2020-11-29 10:34 UTC
^ title

**Comment by zaCade** [comment] 2020-11-29 11:52
I just tested the mentioned frames myself, for me they work as intended.
Could you possibly have an addon that modifies these frames, or something alike?

**Comment by speedwaystar** [comment] 2020-11-30 09:33
thanks. after disabling most of my addons, it works again. i'll try to
figure out which one is causing a conflict.

**Comment by zaCade** [comment] 2020-12-26 14:56
Might be two causes to this, first is simply if you open the frame for the first time during combat we can't touch the frame and there is simply nothing in place to re-attempt the stuff after combat. Second being some addon loading the loadable on demand addons forcefully meaning we didnt notice them being loaded, this is fixed in v3.0.8.
If the issue still presists after updating, make a new issue.

**Closed by zaCade** 2020-12-26 14:56 UTC
