### ISSUE TITLE
BlizzMove Error when trying to use an item

### ISSUE THREAD

**Issue by webdevdave** [Kiatra/BlizzMove#100] opened 2022-10-29 03:47 UTC
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

When right-clicking on an item in my bags, like: Food, Shadowcore Oil, Shaded Sharpening Stone, Disposable Spectrophasic Reanimatoir, etc...* I get a pop-up that says "BlizzMove has been blocked from an action only available to the Blizzard UI."*and the item can not be used.

### Steps to reproduce.

Right click on an item in your bag to use it.

### Expected behavior.

Item should be used/applied normally.

### Errors

```lua
https://i.ibb.co/wpgdf2n/bm-blocked.png
```

**Comment by Numynum** [comment] 2022-10-29 14:17
duplicate of #97

**Closed by Numynum** 2022-10-29 14:17 UTC
Labels: bug, needs-investigation
