### ISSUE TITLE
[Bug Report] Map pin not being put at location specifiec

### ISSUE THREAD

**Issue by RedHarlot** [Kiatra/BlizzMove#107] opened 2022-12-22 20:14 UTC
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

When I put a map pin or tom tom waypoint the pin does not appear on the world map in the location selected.  Additionally, I try to click on a zone area and it is not selected. I have to move the cursor around the map to find the spot that allows me to choose the zone I want.

I disable the addon and the problem is not present.  
I disable TomTom and the problem persists.

### Steps to reproduce.

Load game.
Launch world map
Crtl+left click to place pin

### Expected behavior.

the expected behavior is that the pin should be placed at the spot clicked on by the the player.  As it does when the addon is not active.

### Errors

```lua
none
```

**Comment by Numynum** [comment] 2022-12-25 10:33
Same issue as #105, which is caused by https://github.com/Stanzilla/WoWUIBugs/issues/338
It might get fixed by Blizzard in 10.0.5, but currently on PTR, it's still broken

Resetting the scale of the map frame should fix it (CTRL+right-click the title bar)

**Comment by Numynum** [comment] 2023-01-06 21:50
should be fixed on PTR

**Closed by Numynum** 2023-01-06 21:50 UTC
Labels: bug, version-retail, blame-blizzard
